### ISSUE TITLE
Question about RemovePipelines

### ISSUE THREAD

**Issue by juchom** [AnkurSheel/StatiqHelpers#12]
Hello,

I just found your repo and I'm learning Statiq from it.

I have two questions about this code :

https://github.com/AnkurSheel/StatiqHelpers/blob/01a669baaae0e5ddf6289b5e061cab66a54ed91c/src/StatiqHelpers/Extensions/BootstrapperExtensions.cs#L60-L78

1. Why are you adding a new pipeline in the RemovePipelines method ?

2. What does `ReplaceDocuments` module do in this case ?

Thanks a lot.

**Comment by AnkurSheel** [comment]
Hey,

Adding the `AnalyzeContent` pipeline can be moved out from RemovePipelines and into AddPiplines. Its an oversight. Thanks for pointing that out,

`ReplaceDocuments` replaces the input documents for the `AnalyzeContent` pipeline with  the output documents of all of the pipelines passed as a parameter to it.

Hope that helps

**Comment by juchom** [comment]
Perfect, thanks a lot !
