### ISSUE TITLE
One more question about the PostPipeline

### ISSUE THREAD

**Issue by juchom** [AnkurSheel/StatiqHelpers#13]
I continue to study your pipelines and I'm wondering how the `PostPipeline` knows that it has to use the file `_Layout.cshtml` in the `posts` directory ?

Thanks again !

**Comment by juchom** [comment]
After some digging, I may have found the reason, `.md` files are in `content/posts` and layout is in `input/posts`.

Statiq will see all the files in the same directory and the RenderRazor will look for a layout files first in the same directory as the `md` files and then move up a directory if it doesn't find one ?

Is this the correct ?

**Comment by AnkurSheel** [comment]
That is correct. It will look for a _ViewStart.cshtml file in the same directory as the .md file and move up till it finds one.
